name: Build mod + native (linux-aarch64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest
    outputs:
      native-path: ${{ steps.package.outputs.native }}
    steps:
      - uses: actions/checkout@v4

      - name: Install cross-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu build-essential

      - name: Build joycond (aarch64)
        working-directory: native-src/joycond
        run: |
          make clean || true
          make CC=aarch64-linux-gnu-gcc
          mkdir -p ../out/native/linux-aarch64
          cp joycond ../../src/main/resources/native/linux-aarch64/joycond
          chmod +x ../../src/main/resources/native/linux-aarch64/joycond
      - name: Set output
        id: package
        run: echo "::set-output name=native::src/main/resources/native/linux-aarch64/joycond"

  build-java:
    runs-on: ubuntu-latest
    needs: build-native
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build jar
        run: |
          ./gradlew clean jar --no-daemon

      - name: Upload artifact (jar)
        uses: actions/upload-artifact@v4
        with:
          name: joycon-reindev-mod
          path: build/libs/*.jar
